language: node_js
node_js:
  - '8.6.0'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ShareRoom' ]; then cd .. && eval "mv $currentfolder ShareRoom" && cd generator-ionic; fi
